// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVBmYqkOI8kvpKNDX0WHxL9pwQT0sg92M',
    appId: '1:466019907037:web:8dc49bfcb558893b1ff234',
    messagingSenderId: '466019907037',
    projectId: 'greenbook-f167d',
    authDomain: 'greenbook-f167d.firebaseapp.com',
    storageBucket: 'greenbook-f167d.appspot.com',
    measurementId: 'G-Z3N12RPLQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzmm4illmpj1c-njlnQrdHOjf53tMezek',
    appId: '1:466019907037:android:0de0a4a0591086cc1ff234',
    messagingSenderId: '466019907037',
    projectId: 'greenbook-f167d',
    storageBucket: 'greenbook-f167d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ3_7tvdgtOT71JJroYaJKIvoG-2bCGLw',
    appId: '1:466019907037:ios:6ba07c5e9314700e1ff234',
    messagingSenderId: '466019907037',
    projectId: 'greenbook-f167d',
    storageBucket: 'greenbook-f167d.appspot.com',
    iosBundleId: 'com.example.greenbook',
  );
}
